### PR TITLE
Made SignIn and SignUp : Signup and Signin Page #1

### PR DESCRIPTION
**Pull request by vijaymehrotra**
Solved the Issue no : https://github.com/Ashutosh-777/Utility-Watch/issues/1
I have created the Made SignIn and SignUp Page as specified in the Figma Design..
I have also added the dependency for adding the asset image in the login page in the pubspec.yaml file..
so please before running the project run "flutter pub get" to import all the newly added dependency..

Some of the ScreenShots are:
image
image

### CODE REVIEW

**Comment by Ashutosh-777** [comment]
> Solved the Issue no : #1 I have created the Made SignIn and SignUp Page as specified in the Figma Design.. I have also added the dependency for adding the asset image in the login page in the pubspec.yaml file.. so please before running the project run "flutter pub get" to import all the newly added dependency..
> 
> Some of the ScreenShots are: Screenshot 2023-10-16 090749
> 
> Screenshot 2023-10-16 090815

Screenshots you attached differ from the design in the figma file plz try to duplicate the same design

**Comment by vijaymehrotra** [comment]
Ok will be done till tonight..

**Comment by vijaymehrotra** [comment]
Hello @Ashutosh-777 ,
As you can See I have Updated the Pull Request and updated the code more similar to the Figma design..
Please review my code ..

**Comment by Ashutosh-777** [comment]
image
image

please make the necessary changes, There seems to be problem with Images

**Comment by Ashutosh-777** [comment]
> image image
> 
> please make the necessary changes, There seems to be problem with Images

image
text field look like this when its width exceed width of phone,Fix this as well

**Comment by vijaymehrotra** [comment]
Hy @Ashutosh-777,
Sorry for the inconvenience in the design,
I have updated the code for the large input data in the text form fields.

And as for the image error: in my system the images are showing clearly. 
make sure you follow these commands.

- flutter pub get
- flutter run

And if still no image is displaying

- flutter clean
- flutter pub get
- flutter run

By doing these images must be displayed in the app...
If not the tell me again...

**Comment by Ashutosh-777** [comment]
> Hy @Ashutosh-777, Sorry for the inconvenience in the design, I have updated the code for the large input data in the text form fields.
> 
> And as for the image error: in my system the images are showing clearly. make sure you follow these commands.
> 
> * flutter pub get
> * flutter run
> 
> And if still no image is displaying
> 
> * flutter clean
> * flutter pub get
> * flutter run
> 
> By doing these images must be displayed in the app... If not the tell me again...

Can you share screenshots (Images are still not visible for me)
image
Also one more change needs to be done, I can see lots of spaces left as marked by red pen minimize those spaces to match the design

**Comment by Ashutosh-777** [comment]
> > Hy @Ashutosh-777, Sorry for the inconvenience in the design, I have updated the code for the large input data in the text form fields.
> > And as for the image error: in my system the images are showing clearly. make sure you follow these commands.
> > 
> > * flutter pub get
> > * flutter run
> > 
> > And if still no image is displaying
> > 
> > * flutter clean
> > * flutter pub get
> > * flutter run
> > 
> > By doing these images must be displayed in the app... If not the tell me again...
> 
> Can you share screenshots (Images are still not visible for me) image Also one more change needs to be done, I can see lots of spaces left as marked by red pen minimize those spaces to match the design

Keep the whole thing in center of the screen as in the design

**Comment by Ashutosh-777** [comment]
Plz attach screenshots

**Comment by vijaymehrotra** [comment]
Yes working on it ...

**Comment by vijaymehrotra** [comment]
Hey @Ashutosh-777,
I have updated the code as you can see

image


image

**Comment by vijaymehrotra** [comment]
and for the image issue
you should do flutter pub get 
then flutter run to solve the issue

**Pull request merged**
