### PR TITLE
Solved the issue 8:Objective Page #8

### PR DESCRIPTION
**Pull request by vijaymehrotra**
Solved the Issue no : https://github.com/Ashutosh-777/Utility-Watch/issues/8
I have created the Objective screen as specified in the Figma Design..
I have also added the dependency "percent_indicator 4.2.3" in the pubspec.yaml file..
so please before running the project run "flutter pub get" to import all the newly added dependency..

The Screenshot for the objective screen is here:
image

### CODE REVIEW

**Comment by vijaymehrotra** [comment]
Hello @Ashutosh-777 ,
I was happy to work with you and this project and community,
and i will be happy to work with you in future..😊.

**Comment by Ashutosh-777** [comment]
> Solved the Issue no : #8 I have created the Objective screen as specified in the Figma Design.. I have also added the dependency "percent_indicator 4.2.3" in the pubspec.yaml file.. so please before running the project run "flutter pub get" to import all the newly added dependency..
> 
> The Screenshot for the objective screen is here: image

Thanks for Contributing
We have one more page related to the objective Page (having very minor changes from the one you made) If interested then reply to this comment. (If you reply then issue will be directly assigned to you)

**Comment by vijaymehrotra** [comment]
Yes I would be happy to work..

**Comment by vijaymehrotra** [comment]
> > Solved the Issue no : #8 I have created the Objective screen as specified in the Figma Design.. I have also added the dependency "percent_indicator 4.2.3" in the pubspec.yaml file.. so please before running the project run "flutter pub get" to import all the newly added dependency..
> > The Screenshot for the objective screen is here: image
> 
> Thanks for Contributing We have one more page related to the objective Page (having very minor changes from the one you made) If interested then reply to this comment. (If you reply then issue will be directly assigned to you)


Yes I would be happy to work...

**Comment by Ashutosh-777** [comment]
> > > Solved the Issue no : #8 I have created the Objective screen as specified in the Figma Design.. I have also added the dependency "percent_indicator 4.2.3" in the pubspec.yaml file.. so please before running the project run "flutter pub get" to import all the newly added dependency..
> > > The Screenshot for the objective screen is here: image
> > 
> > 
> > Thanks for Contributing We have one more page related to the objective Page (having very minor changes from the one you made) If interested then reply to this comment. (If you reply then issue will be directly assigned to you)
> 
> Yes I would be happy to work...
@vijaymehrotra you can work on #15

**Pull request merged**
